/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Q6 */

#ifndef _Included_Q6
#define _Included_Q6
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Q6
 * Method:    cfunction
 * Signature: ()V
 */

JNIEXPORT jlong JNICALL
Java_Q6_cCalculateDotProduct
(JNIEnv *, jobject, jintArray,jintArray);


#ifdef __cplusplus
}
#endif
#endif
